# Generated by Django 4.0 on 2022-04-22 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.TimeField()),
                ('arival', models.TimeField()),
                ('adultcost', models.FloatField()),
                ('childcost', models.FloatField()),
                ('fromP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPB', to='main.places')),
                ('toP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPB', to='main.places')),
            ],
        ),
    ]
