# Generated by Django 4.0 on 2022-04-23 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_buschart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('adult', models.BigIntegerField()),
                ('child', models.BigIntegerField()),
                ('baby', models.BigIntegerField()),
                ('totalcost', models.FloatField()),
                ('departureDate', models.DateField()),
                ('payment', models.CharField(max_length=120)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buschart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
