# Generated by Django 4.0 on 2022-04-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bustrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustrip',
            name='baby',
        ),
    ]
