# Generated by Django 4.0 on 2022-04-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_bustrip_baby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bustrip',
            old_name='flight',
            new_name='bus',
        ),
    ]
